//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringRequest", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class RecurringRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Amount amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string originalReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recurringReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Amount amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount {
            get {
                return this.merchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantAccountField, value) != true)) {
                    this.merchantAccountField = value;
                    this.RaisePropertyChanged("merchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string originalReference {
            get {
                return this.originalReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.originalReferenceField, value) != true)) {
                    this.originalReferenceField = value;
                    this.RaisePropertyChanged("originalReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringReference {
            get {
                return this.recurringReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringReferenceField, value) != true)) {
                    this.recurringReferenceField = value;
                    this.RaisePropertyChanged("recurringReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperEmail {
            get {
                return this.shopperEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperEmailField, value) != true)) {
                    this.shopperEmailField = value;
                    this.RaisePropertyChanged("shopperEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference {
            get {
                return this.shopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperReferenceField, value) != true)) {
                    this.shopperReferenceField = value;
                    this.RaisePropertyChanged("shopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount", Namespace="http://common.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class Amount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string currencyField;
        
        private long valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringResult", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class RecurringResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pspReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspReference {
            get {
                return this.pspReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.pspReferenceField, value) != true)) {
                    this.pspReferenceField = value;
                    this.RaisePropertyChanged("pspReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://common.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Error> errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Type> typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Error> error {
            get {
                return this.errorField;
            }
            set {
                if ((this.errorField.Equals(value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Type> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://common.services.adyen.com")]
    public enum Error : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAllowed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAmountSpecified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToDetermineVariant = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMerchantAccount = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestMissing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToProcess = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentDetailsAreNotSupported = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://common.services.adyen.com")]
    public enum Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @internal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        validation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        security = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        configuration = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisableRequest", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class DisableRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recurringDetailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount {
            get {
                return this.merchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantAccountField, value) != true)) {
                    this.merchantAccountField = value;
                    this.RaisePropertyChanged("merchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference {
            get {
                return this.recurringDetailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringDetailReferenceField, value) != true)) {
                    this.recurringDetailReferenceField = value;
                    this.RaisePropertyChanged("recurringDetailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference {
            get {
                return this.shopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperReferenceField, value) != true)) {
                    this.shopperReferenceField = value;
                    this.RaisePropertyChanged("shopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisableResult", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class DisableResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetailsRequest", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class RecurringDetailsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Recurring recurringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customReference {
            get {
                return this.customReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.customReferenceField, value) != true)) {
                    this.customReferenceField = value;
                    this.RaisePropertyChanged("customReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount {
            get {
                return this.merchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantAccountField, value) != true)) {
                    this.merchantAccountField = value;
                    this.RaisePropertyChanged("merchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Recurring recurring {
            get {
                return this.recurringField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringField, value) != true)) {
                    this.recurringField = value;
                    this.RaisePropertyChanged("recurring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference {
            get {
                return this.shopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperReferenceField, value) != true)) {
                    this.shopperReferenceField = value;
                    this.RaisePropertyChanged("shopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recurring", Namespace="http://payment.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class Recurring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recurringDetailNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract {
            get {
                return this.contractField;
            }
            set {
                if ((object.ReferenceEquals(this.contractField, value) != true)) {
                    this.contractField = value;
                    this.RaisePropertyChanged("contract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailName {
            get {
                return this.recurringDetailNameField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringDetailNameField, value) != true)) {
                    this.recurringDetailNameField = value;
                    this.RaisePropertyChanged("recurringDetailName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetailsResult", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class RecurringDetailsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetail[] detailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastKnownShopperEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                if ((this.creationDateField.Equals(value) != true)) {
                    this.creationDateField = value;
                    this.RaisePropertyChanged("creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetail[] details {
            get {
                return this.detailsField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsField, value) != true)) {
                    this.detailsField = value;
                    this.RaisePropertyChanged("details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastKnownShopperEmail {
            get {
                return this.lastKnownShopperEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.lastKnownShopperEmailField, value) != true)) {
                    this.lastKnownShopperEmailField = value;
                    this.RaisePropertyChanged("lastKnownShopperEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference {
            get {
                return this.shopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperReferenceField, value) != true)) {
                    this.shopperReferenceField = value;
                    this.RaisePropertyChanged("shopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetail", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class RecurringDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.BankAccount bankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Card cardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ELV elvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recurringDetailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string variantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.BankAccount bank {
            get {
                return this.bankField;
            }
            set {
                if ((object.ReferenceEquals(this.bankField, value) != true)) {
                    this.bankField = value;
                    this.RaisePropertyChanged("bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Card card {
            get {
                return this.cardField;
            }
            set {
                if ((object.ReferenceEquals(this.cardField, value) != true)) {
                    this.cardField = value;
                    this.RaisePropertyChanged("card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                if ((this.creationDateField.Equals(value) != true)) {
                    this.creationDateField = value;
                    this.RaisePropertyChanged("creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ELV elv {
            get {
                return this.elvField;
            }
            set {
                if ((object.ReferenceEquals(this.elvField, value) != true)) {
                    this.elvField = value;
                    this.RaisePropertyChanged("elv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference {
            get {
                return this.recurringDetailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringDetailReferenceField, value) != true)) {
                    this.recurringDetailReferenceField = value;
                    this.RaisePropertyChanged("recurringDetailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string variant {
            get {
                return this.variantField;
            }
            set {
                if ((object.ReferenceEquals(this.variantField, value) != true)) {
                    this.variantField = value;
                    this.RaisePropertyChanged("variant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://payment.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ibanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.bankAccountNumberField, value) != true)) {
                    this.bankAccountNumberField = value;
                    this.RaisePropertyChanged("bankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocationId {
            get {
                return this.bankLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.bankLocationIdField, value) != true)) {
                    this.bankLocationIdField = value;
                    this.RaisePropertyChanged("bankLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bankNameField, value) != true)) {
                    this.bankNameField = value;
                    this.RaisePropertyChanged("bankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bic {
            get {
                return this.bicField;
            }
            set {
                if ((object.ReferenceEquals(this.bicField, value) != true)) {
                    this.bicField = value;
                    this.RaisePropertyChanged("bic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countryCodeField, value) != true)) {
                    this.countryCodeField = value;
                    this.RaisePropertyChanged("countryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iban {
            get {
                return this.ibanField;
            }
            set {
                if ((object.ReferenceEquals(this.ibanField, value) != true)) {
                    this.ibanField = value;
                    this.RaisePropertyChanged("iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ownerName {
            get {
                return this.ownerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerNameField, value) != true)) {
                    this.ownerNameField = value;
                    this.RaisePropertyChanged("ownerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://payment.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Address billingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cvcField;
        
        private string expiryMonthField;
        
        private string expiryYearField;
        
        private string holderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string issueNumberField;
        
        private string numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.billingAddressField, value) != true)) {
                    this.billingAddressField = value;
                    this.RaisePropertyChanged("billingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cvc {
            get {
                return this.cvcField;
            }
            set {
                if ((object.ReferenceEquals(this.cvcField, value) != true)) {
                    this.cvcField = value;
                    this.RaisePropertyChanged("cvc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string expiryMonth {
            get {
                return this.expiryMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.expiryMonthField, value) != true)) {
                    this.expiryMonthField = value;
                    this.RaisePropertyChanged("expiryMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string expiryYear {
            get {
                return this.expiryYearField;
            }
            set {
                if ((object.ReferenceEquals(this.expiryYearField, value) != true)) {
                    this.expiryYearField = value;
                    this.RaisePropertyChanged("expiryYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string holderName {
            get {
                return this.holderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.holderNameField, value) != true)) {
                    this.holderNameField = value;
                    this.RaisePropertyChanged("holderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string issueNumber {
            get {
                return this.issueNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.issueNumberField, value) != true)) {
                    this.issueNumberField = value;
                    this.RaisePropertyChanged("issueNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startMonth {
            get {
                return this.startMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.startMonthField, value) != true)) {
                    this.startMonthField = value;
                    this.RaisePropertyChanged("startMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startYear {
            get {
                return this.startYearField;
            }
            set {
                if ((object.ReferenceEquals(this.startYearField, value) != true)) {
                    this.startYearField = value;
                    this.RaisePropertyChanged("startYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELV", Namespace="http://payment.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class ELV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountHolderName {
            get {
                return this.accountHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.accountHolderNameField, value) != true)) {
                    this.accountHolderNameField = value;
                    this.RaisePropertyChanged("accountHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.bankAccountNumberField, value) != true)) {
                    this.bankAccountNumberField = value;
                    this.RaisePropertyChanged("bankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocation {
            get {
                return this.bankLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.bankLocationField, value) != true)) {
                    this.bankLocationField = value;
                    this.RaisePropertyChanged("bankLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocationId {
            get {
                return this.bankLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.bankLocationIdField, value) != true)) {
                    this.bankLocationIdField = value;
                    this.RaisePropertyChanged("bankLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bankNameField, value) != true)) {
                    this.bankNameField = value;
                    this.RaisePropertyChanged("bankName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://common.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string houseNumberOrNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateOrProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseNumberOrName {
            get {
                return this.houseNumberOrNameField;
            }
            set {
                if ((object.ReferenceEquals(this.houseNumberOrNameField, value) != true)) {
                    this.houseNumberOrNameField = value;
                    this.RaisePropertyChanged("houseNumberOrName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalCodeField, value) != true)) {
                    this.postalCodeField = value;
                    this.RaisePropertyChanged("postalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.stateOrProvinceField, value) != true)) {
                    this.stateOrProvinceField = value;
                    this.RaisePropertyChanged("stateOrProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreTokenRequest", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class StoreTokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.BankAccount bankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Card cardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ELV elvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Recurring recurringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.BankAccount bank {
            get {
                return this.bankField;
            }
            set {
                if ((object.ReferenceEquals(this.bankField, value) != true)) {
                    this.bankField = value;
                    this.RaisePropertyChanged("bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Card card {
            get {
                return this.cardField;
            }
            set {
                if ((object.ReferenceEquals(this.cardField, value) != true)) {
                    this.cardField = value;
                    this.RaisePropertyChanged("card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ELV elv {
            get {
                return this.elvField;
            }
            set {
                if ((object.ReferenceEquals(this.elvField, value) != true)) {
                    this.elvField = value;
                    this.RaisePropertyChanged("elv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount {
            get {
                return this.merchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantAccountField, value) != true)) {
                    this.merchantAccountField = value;
                    this.RaisePropertyChanged("merchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.Recurring recurring {
            get {
                return this.recurringField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringField, value) != true)) {
                    this.recurringField = value;
                    this.RaisePropertyChanged("recurring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperEmail {
            get {
                return this.shopperEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperEmailField, value) != true)) {
                    this.shopperEmailField = value;
                    this.RaisePropertyChanged("shopperEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference {
            get {
                return this.shopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.shopperReferenceField, value) != true)) {
                    this.shopperReferenceField = value;
                    this.RaisePropertyChanged("shopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreTokenResult", Namespace="http://recurring.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class StoreTokenResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rechargeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recurringDetailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rechargeReference {
            get {
                return this.rechargeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.rechargeReferenceField, value) != true)) {
                    this.rechargeReferenceField = value;
                    this.RaisePropertyChanged("rechargeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference {
            get {
                return this.recurringDetailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.recurringDetailReferenceField, value) != true)) {
                    this.recurringDetailReferenceField = value;
                    this.RaisePropertyChanged("recurringDetailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://recurring.services.adyen.com", ConfigurationName="Adyen.Test.RecurringSoapService.RecurringPortType")]
    public interface RecurringPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult deactivateRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> deactivateRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableResult disable(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableResult> disableAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult initialiseRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> initialiseRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsResult listRecurringDetails(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsResult> listRecurringDetailsAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenResult storeToken(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenResult> storeTokenAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult submitRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recurringResult")]
        System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> submitRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecurringPortTypeChannel : Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecurringPortTypeClient : System.ServiceModel.ClientBase<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringPortType>, Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringPortType {
        
        public RecurringPortTypeClient() {
        }
        
        public RecurringPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecurringPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecurringPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecurringPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult deactivateRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.deactivateRecurring(recurringRequest);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> deactivateRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.deactivateRecurringAsync(recurringRequest);
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableResult disable(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableRequest request) {
            return base.Channel.disable(request);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableResult> disableAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.DisableRequest request) {
            return base.Channel.disableAsync(request);
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult initialiseRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.initialiseRecurring(recurringRequest);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> initialiseRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.initialiseRecurringAsync(recurringRequest);
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsResult listRecurringDetails(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsRequest request) {
            return base.Channel.listRecurringDetails(request);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsResult> listRecurringDetailsAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringDetailsRequest request) {
            return base.Channel.listRecurringDetailsAsync(request);
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenResult storeToken(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenRequest request) {
            return base.Channel.storeToken(request);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenResult> storeTokenAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.StoreTokenRequest request) {
            return base.Channel.storeTokenAsync(request);
        }
        
        public Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult submitRecurring(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.submitRecurring(recurringRequest);
        }
        
        public System.Threading.Tasks.Task<Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringResult> submitRecurringAsync(Ucommerce.Transactions.Payments.Adyen.Adyen.Test.RecurringSoapService.RecurringRequest recurringRequest) {
            return base.Channel.submitRecurringAsync(recurringRequest);
        }
    }
}
