//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationRequest", Namespace="http://notification.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class NotificationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool liveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem[] notificationItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool live {
            get {
                return this.liveField;
            }
            set {
                if ((this.liveField.Equals(value) != true)) {
                    this.liveField = value;
                    this.RaisePropertyChanged("live");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem[] notificationItems {
            get {
                return this.notificationItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.notificationItemsField, value) != true)) {
                    this.notificationItemsField = value;
                    this.RaisePropertyChanged("notificationItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationRequestItem", Namespace="http://notification.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class NotificationRequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.anyType2anyTypeMap additionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Amount amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eventCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime eventDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantAccountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ArrayOfString operationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string originalReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pspReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.anyType2anyTypeMap additionalData {
            get {
                return this.additionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.additionalDataField, value) != true)) {
                    this.additionalDataField = value;
                    this.RaisePropertyChanged("additionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Amount amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eventCode {
            get {
                return this.eventCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.eventCodeField, value) != true)) {
                    this.eventCodeField = value;
                    this.RaisePropertyChanged("eventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                if ((this.eventDateField.Equals(value) != true)) {
                    this.eventDateField = value;
                    this.RaisePropertyChanged("eventDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccountCode {
            get {
                return this.merchantAccountCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantAccountCodeField, value) != true)) {
                    this.merchantAccountCodeField = value;
                    this.RaisePropertyChanged("merchantAccountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantReference {
            get {
                return this.merchantReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantReferenceField, value) != true)) {
                    this.merchantReferenceField = value;
                    this.RaisePropertyChanged("merchantReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ArrayOfString operations {
            get {
                return this.operationsField;
            }
            set {
                if ((object.ReferenceEquals(this.operationsField, value) != true)) {
                    this.operationsField = value;
                    this.RaisePropertyChanged("operations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string originalReference {
            get {
                return this.originalReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.originalReferenceField, value) != true)) {
                    this.originalReferenceField = value;
                    this.RaisePropertyChanged("originalReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentMethodField, value) != true)) {
                    this.paymentMethodField = value;
                    this.RaisePropertyChanged("paymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspReference {
            get {
                return this.pspReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.pspReferenceField, value) != true)) {
                    this.pspReferenceField = value;
                    this.RaisePropertyChanged("pspReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount", Namespace="http://common.services.adyen.com")]
    [System.SerializableAttribute()]
    public partial class Amount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="anyType2anyTypeMap", Namespace="http://notification.services.adyen.com", ItemName="entry")]
    [System.SerializableAttribute()]
    public class anyType2anyTypeMap : System.Collections.Generic.List<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.entry> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://notification.services.adyen.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entry", Namespace="http://notification.services.adyen.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.anyType2anyTypeMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Amount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Type))]
    public partial class entry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://common.services.adyen.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequestItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.anyType2anyTypeMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Amount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Type))]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Error> errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faultActorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object faultDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faultStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Type> typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Error> error {
            get {
                return this.errorField;
            }
            set {
                if ((this.errorField.Equals(value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faultActor {
            get {
                return this.faultActorField;
            }
            set {
                if ((object.ReferenceEquals(this.faultActorField, value) != true)) {
                    this.faultActorField = value;
                    this.RaisePropertyChanged("faultActor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faultCodeField, value) != true)) {
                    this.faultCodeField = value;
                    this.RaisePropertyChanged("faultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object faultDetail {
            get {
                return this.faultDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.faultDetailField, value) != true)) {
                    this.faultDetailField = value;
                    this.RaisePropertyChanged("faultDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                if ((object.ReferenceEquals(this.faultStringField, value) != true)) {
                    this.faultStringField = value;
                    this.RaisePropertyChanged("faultString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.Type> type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://common.services.adyen.com")]
    public enum Error : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAllowed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAmountSpecified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardNumber = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToDetermineVariant = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVCisNotTheRightLength = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLoyaltyAmountSpecified = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPaRes3dSecure = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionAlreadyUsed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecurringNotEnabled = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBankAccountNumber = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidVariant = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBankDetailsMissing = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBankCountry = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankCountryNotSupported = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenInvoiceLinesMissing = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenInvoiceLineInvalid = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenInvoiceLinesInvalidTotalAmount = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDateOfBirth = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBillingAddress = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDeliveryAddress = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidShopperName = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingShopperEmail = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingShopperReference = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingPhoneNumber = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobilePhoneNumberOnly = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPhoneNumber = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecurringInvalidContract = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankAccountOrBankLocationIdNotValid = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountHolderMissing = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardHolderNameMissing = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidExpiry = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingMerchantReference = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingAddressCityProblem = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingAddressStreetProblem = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingAddressHouseNumberOrNameProblem = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingAddressCountryProblem = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingAddressStateOrProvinceProblem = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenInvoiceFailedToRetrieveDetails = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAmount = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnsupportedCurrency = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecurringRequiredFields = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardExpiryOnInPast = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardExpiry = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankNameOrBankLocationIsNotValid = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIdealMerchantReturnUrl = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardStartDateInFuture = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIssuerCountryCode = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSocialSecurityNumber = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryAddressCityProblem = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryAddressStreetProblem = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryAddressHouseNumberOrNameProblem = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryAddressCountryProblem = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryAddressStateOrProvinceProblem = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidInstallments = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCVC = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingAdditionalData = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingAcquirer = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingAuthorisationMid = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingFields = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingRequiredField = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNumberOfRequests = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayoutStoreDetailNotAllowed = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIBAN = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InconsistentIban = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBIC = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAutoCaptureDelay = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenerationDateMissing = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenerationDateParseError = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenerationDateNotInRange = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToLoadPrivateKey = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToDecryptData = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JSONParseError = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidShopperReference = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidShopperEmail = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSelectedBrand = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidRecurringContract = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidRecurringDetailName = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAdditionalData = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingAdditionalDataField = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAdditionalDataField = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPspEchoData = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidShopperStatement = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidShopperIP = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_MissingInvoiceProject = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_MissingInvoiceBatch = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_MissingCreditorAccount = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_MissingProjectCode = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_CreditorAccountNotFound = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_ProjectNotFound = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_InvoiceProjectCouldNotBeCreated = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_InvoiceBatchAlreadyExists = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_InvoiceBatchCouldNotBeCreated = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice_InvoiceBatchPeriodExceeded = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingInvoice = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingCreditorAccountCode = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingInvoiceProjectAccountCode = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingDebtorCode = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingFirstName = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingLastName = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingStreetAddress = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingDebtorPostalCode = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingCity = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingCountryCode = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingAddressCountryCode = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingEmailAddress = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingDebtorPhoneNumber = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingInvoicePayment = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMissingReference = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidCreditorAccount = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidInvoiceProject = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidDebtor = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidPaymentAmount = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidPaymentCurrency = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceInvalidDebtorType = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceDoesNotExists = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceDoesNotExistsForDebtor = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoicePaymentAmountTooHigh = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceAlreadyPaid = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingDebtor = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorMissingAccountCode = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorAlreadyExists = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorNotFound = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditInvoiceWithNewDebtorNotAllowed = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorAndInvoiceDebtorCodeMismatch = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DebtorAndInvoiceProjectCodeMismatch = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExplicitInvoiceAlreadyExists = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceMandatoryField = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoInvoicesFoundForPaymentReference = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorStoreDebtor = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorStoreInvoice = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorCheckInvoiceReference = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorSearchInvoices = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorNoInvoiceConfiguration = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceErrorInvalidInvoiceConfiguration = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeContractNotFound = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeTooManyPaymentDetails = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeInvalidContract = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeDetailNotFound = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeFailedToDisable = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeDetailNotAvailableForContract = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechargeNoApplicableContractTypeLeft = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMerchantAccount = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestMissing = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToProcess = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentDetailsAreNotSupported = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginalPspReferenceInvalidForThisEnvironment = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAcquirerAccount = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationAuthorisationMid = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationAcquirerPassword = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationApiKey = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationRedirectUrl = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationAcquirerAccountData = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationCurrencyCode = 154,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationAuthorisationTerminalId = 155,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationSerialNumber = 156,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationPassword = 157,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationProjectId = 158,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationMerchantCategoryCode = 159,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidConfigurationMerchantName = 160,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://common.services.adyen.com")]
    public enum Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @internal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        validation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        security = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        configuration = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://notification.services.adyen.com", ConfigurationName="Adyen.Test.NotificationSoapService.NotificationPortType")]
    public interface NotificationPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="notificationResponse")]
        string sendNotification(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="notificationResponse")]
        System.Threading.Tasks.Task<string> sendNotificationAsync(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest notification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificationPortTypeChannel : UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationPortTypeClient : System.ServiceModel.ClientBase<UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationPortType>, UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationPortType {
        
        public NotificationPortTypeClient() {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendNotification(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest notification) {
            return base.Channel.sendNotification(notification);
        }
        
        public System.Threading.Tasks.Task<string> sendNotificationAsync(UCommerce.Transactions.Payments.Adyen.Adyen.Test.NotificationSoapService.NotificationRequest notification) {
            return base.Channel.sendNotificationAsync(notification);
        }
    }
}
